trigger:
- main

stages:
  - stage: Deploy_Ingress
    displayName: Deploy Ingress
    jobs:
      - job: Deploy
        displayName: Deploy Ingress
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'akssc'
            manifests: '$(System.DefaultWorkingDirectory)/ingress.yaml'